Basics:
  SEED: 42
  CREATE_OVERLAID_VIDEO: true
  FRAMES_PER_SECOND: 10
  OUT_VIDEO_SIMULATION_DIR: data/simulated/strong_yellow/videos/
  OUT_SIMULATION_DIR: data/simulated/strong_yellow/
  OUT_METADATA_PATH: data/simulated/strong_yellow.csv
  SIMULATE_FROM_EVERY_N_INPUT_PAIRS: 1

Metadata: data/validation/rotated/valid_frames_rotated.csv

Frame:
  ORIGINAL_IMAGE_HEIGHT: 1024
  ORIGINAL_IMAGE_WIDTH: 1024
  WINDOW_INIT_SIZE: [512, 512]
  MAX_STEP_SIZE: 2
  ALLOW_UPDATING_COORDINATES: true
  ALLOW_UPDATING_STEP: true
  ORIENTATION_INIT_RANGE: [-10, 10]
  ORIENTATION_MAX_ADJUSTMENT: 5
  ORIENTATION_ALLOW_UPDATING_ANGLE: false
  TRANSFORMATION_USE_ROTATION: false
  TRANSFORMATION_USE_ELASTIC: false
  TRANSFORMATION_USE_CENTER_CROP: false
  TRANSFORMATION_CC_REFINEMENT_UPPER_BOUND: 64
  TRANSFORMATION_USE_RESIZE: true

Transformations:
  HORIZONAL_FLIP_PROB: 0.0
  VERTICAL_FLIP_PROB: 0.0
  ROTATE_RANGE: [0, 5]
  ROTATE_PROB: 0.8          # The probability of applying rotation
  ELASTIC_ALPHA: [0, 2]     # A random number will be choosen between this range
  ELASTIC_SIGMA: [0, 30]    # A random number will be choosen between this range
  ELASTIC_ALPHA_AFFINE: [0, 20]
  ELASTIC_PROB: 0.5         # The probability of applying elastic transformation

Video:
  VIDEO_HEIGHT: 1024
  VIDEO_WIDTH: 1024
  NUM_REQUIRED_FRAMES: 100    # Number of frames to be generated for each video