Basics:
  SEED: 42
  CREATE_OVERLAID_VIDEO: True
  FRAMES_PER_SECOND: 5
  VIDEOS_OUT_DIR: data/simulated/weak_yellow/videos/
  VIDEOS_IDS_PREFIX: Y
  OUT_SIMULATION_DIR: data/simulated/weak_yellow/
  OUT_METADATA_PATH: data/simulated/weak_yellow.csv

BackgroundMetadata:
  - data/backgrounds/metadata/yellow_yback00.csv
  - data/backgrounds/metadata/yellow_yback01.csv
  - data/backgrounds/metadata/yellow_yback02.csv
  - data/backgrounds/metadata/yellow_yback10.csv
  - data/backgrounds/metadata/yellow_yback20.csv
  - data/backgrounds/metadata/yellow_yback30.csv
  - data/backgrounds/metadata/yellow_yback40.csv
  - data/backgrounds/metadata/yellow_yback50.csv
  - data/backgrounds/metadata/yellow_yback51.csv
  - data/backgrounds/metadata/yellow_yback52.csv
  - data/backgrounds/metadata/yellow_yback53.csv
  - data/backgrounds/metadata/yellow_Cell00-010.csv
  - data/backgrounds/metadata/yellow_Cell01-022.csv
  - data/backgrounds/metadata/yellow_Cell02-032.csv
  - data/backgrounds/metadata/yellow_DJI06_109.csv

RealObjectMetadata:
  - data/foreground/metadata/stage3_real.csv
  - data/foreground/metadata/stage4_real.csv
  - data/foreground/metadata/stage5_real.csv
  - data/foreground/metadata/stage6_real.csv
  - data/foreground/metadata/stage7_real.csv

FakePatchMetadata:
  - data/foreground/metadata/stage3_fake.csv
  - data/foreground/metadata/stage4_fake.csv
  - data/foreground/metadata/stage5_fake.csv
  - data/foreground/metadata/stage6_fake.csv
  - data/foreground/metadata/stage7_fake.csv

Frame:
  FRAME_MOVEMENT_RANGE: [0, 10]   #  range of pixels to shift the frame.
  NODE_MOVEMENT_RANGE: [0, 5]
  NUM_REALS_PER_FRAME: [10, 100]  # 10 to 100 real objects per frame
  NUM_FAKES_PER_FRAME: [10, 100]   # 10 to 100 fake patches per frame
  RECOVERY_VARIANCE: 3
  ALLOW_LEAVE_FRAME: false       # if false does not allow the heads to leave the frame when moving the heads themselves. 
  RECOVERY_AREA_EXPANSION: 3     # When recoverying the removed frames, expand the area where the newly added samples will be distributed in that area.
  CHANGE_DIRECTION_PROBABILITY: 0.1

Transformations:
  HORIZONAL_FLIP_PROB: 0.0
  VERTICAL_FLIP_PROB: 0.0
  ROTATE_RANGE: [1, 5]
  ROTATE_PROB: 0.2          # The probability of applying rotation
  ELASTIC_ALPHA: [0, 2]     # A random number will be choosen between this range
  ELASTIC_SIGMA: [0, 10]    # A random number will be choosen between this range
  ELASTIC_ALPHA_AFFINE: [0, 15]
  ELASTIC_PROB: 0.2         # The probability of applying elastic transformation

Video:
  VIDEO_HEIGHT: 1024
  VIDEO_WIDTH: 1024
  VIDEO_PER_BACKGROUND: 40    # The number of videos to be generated per background. 
  NUM_REQUIRED_FRAMES: 60    # Number of frames to be generated for each video