videos_meta_csv_path: data/videos/yellow_back_metadata.csv
output_metadata_path: data/vi/backgrounds/yellow_frames_metadata.csv
frame_extension: .png
swap_color: null
#  source: [0, 30] # yellow
#  destin: [25, 40] # green
transformer:
  height: 1024
  width: 1024
  rotation_angle: 45
  rotation_p: 0.5
  elast_p: 0.5
  trfm_index: 0  # No transformations. 
