segmented_images_meta_csv_path: data/segmented/valid_segmented_meta.csv
real_metadata_path: data/simulation/foreground/valid_real_yellow.csv
fake_metadata_path: data/simulation/foreground/valid_fake_yellow.csv
segment_extension: .png
min_object_size_in_pixel: 400
num_fakes_per_real: 10
swap_color: null
#  source: [25, 40] # green in hsv
#  destin: [0, 30] # yellow in hsv
transformer:
  height: 1024
  width: 1024
  rotation_angle: 45
  rotation_p: 0.5
  elast_p: 0.5
  trfm_index: 0  # Null transform.
