background_meta: data/simulation/background/yellow_backgrounds.csv
real_object_meta: data/simulation/foreground/valid_real_yellow.csv 
fake_patch_meta: data/simulation/foreground/valid_fake_yellow.csv
real_trfm_idx: 9   # the transformation idx for real objects. 
fake_trfm_idx: 9   # the transformation idx for fake objects. 
img_trfm_idx: 0    # The color transformation for the whole simulated image. 
min_num_objects: 10
max_num_objects: 100
min_num_patches: 10
max_num_patches: 100
num_loc_finder_try: 50
iou_threshold: 0.6
image_heigth: 1024
image_width: 1024
image_extension: .jpg
dataset_size: 10000
phase: valid  # options: `train`, `valid`
out_dir: new_simulated_data/simulation/weak/train_data
out_dataset_path: new_simulated_data/ddm/simulation/weak/train_dataset_yellow.csv
